### ISSUE TITLE
Attempting a connection fails: missing field `datapackage_version`

### ISSUE THREAD

**Issue by subenji** [ryanisaacg/archipelago_rs#1]
https://github.com/ryanisaacg/archipelago_rs/blob/89580f293274cdbe34ef3dbb9c3b431b6e986bd7/src/protocol.rs#L190-L203

`datapackage_version` was removed in Archipelago 0.3.7 and is now preventing any connections.

https://github.com/ArchipelagoMW/Archipelago/commit/2cdd03f78624e07f2a943381500f93e8c3b5cb23#diff-2fdfc3f0c7765b3008f036da659a2b55754707a68a56e27b396fedb902e2cbe9

**Comment by ryanisaacg** [comment]
Thanks for the report! Fixed that up in 73a7fcfe94949cf9fe24a2d276b35f03f8f14e3f
