### ISSUE TITLE
Better way to send while also waiting on recv

### ISSUE THREAD

**Issue by Gaelan** [ryanisaacg/archipelago_rs#4]
Currently, `recv` blocks (or does the async equivalent thereof) while holding the `&mut ArchipelagoClient`, so there isn't a great way to send items while also receiving them. This seems to work well enough as a workaround:

```rust
    let (recv_tx, recv_rx) = std::sync::mpsc::channel();
    let (send_tx, mut send_rx) = tokio::sync::mpsc::unbounded_channel();

    rt.spawn(async move {
        loop {
            select!(
                msg = client.recv().fuse() => if let Ok(Some(msg)) = msg {
                    recv_tx.send(msg).unwrap();
                } else {
                    impossible(&format!("none or invalid msg: {:?}", &msg));
                },
                msg = send_rx.recv().fuse() => if let Some(msg) = msg {
                    client.send(msg).await.unwrap();
                }
            );
        }
    });

    // stash recv_rx and send_tx for later use from the main thread
```

(Don't get hung up too much on the std vs tokio channels, this makes sense for my arrangement but using Tokio for both is probably fine.)

This seems to work, but just drops the unfinished `recv` future when we have something to send—which raises the question of whether there's a race condition where we have a message to send just as `recv` is processing an incoming message, which might get dropped silently.

**Comment by ryanisaacg** [comment]
This was a fun little trip where I learned a bit more about how streams work. The new `split` API on the `ArchipelagoClient` should give you what you need!
