### ISSUE TITLE
Adding a License to the Project

### ISSUE THREAD

**Issue by jcbantuelle** [ryanisaacg/archipelago_rs#7]
Thank you so much for creating this library, it's extremely helpful. One thing I noticed though is that it doesn't seem to have a license and I was wondering if you'd be open to adding one.

I'm working on a game implementation atm that would benefit immensely from being able to leverage this.

**Comment by ryanisaacg** [comment]
Oh good catch. I'll probably chuck MIT on it to match Archipelago, so all you should need is an attribution for archipelago RS

**Comment by ryanisaacg** [comment]
Added the MIT license!

**Comment by justin-bantuelle** [comment]
Thank you so much!
